/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CadastroBarbeiroController;
import controller.Helper.BarbeiroHelper;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Adriano Pavaneli
 */
public class CadastroBarbeiroView extends javax.swing.JFrame {
    
    private final CadastroBarbeiroController controller;
    private final BarbeiroHelper helper;

    /**
     * Creates new form CadastroBarbeiroView
     */
    public CadastroBarbeiroView() throws SQLException, ParseException {
        initComponents();
        controller = new CadastroBarbeiroController(this);
        helper = new BarbeiroHelper(this);
        TxtCadId.setEnabled(false);
        TxtCadNome.setEnabled(false);               
        BtnInserir.setEnabled(true);
        BtnAlterar.setEnabled(true);
        BtnExcluir.setEnabled(true);
        BtnSalvar.setEnabled(false);
        BtnCancelar.setEnabled(false);
        BtnFechar.setEnabled(true);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarbeiro = new javax.swing.JTable();
        BtnInserir = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        LblId = new javax.swing.JLabel();
        BtnExcluir = new javax.swing.JButton();
        LblNome = new javax.swing.JLabel();
        BtnFechar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        TxtCadId = new javax.swing.JTextField();
        TxtCadNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Barbeiros");
        setLocation(new java.awt.Point(550, 250));

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        TableBarbeiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableBarbeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBarbeiroMouseClicked(evt);
            }
        });
        TableBarbeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableBarbeiroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableBarbeiroKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TableBarbeiro);

        BtnInserir.setText("Inserir");
        BtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserirActionPerformed(evt);
            }
        });

        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        LblId.setText("Id");

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        LblNome.setText("Nome:");

        BtnFechar.setText("Fechar");
        BtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFecharActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCadId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblId))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblNome)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TxtCadNome)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(BtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblId)
                    .addComponent(LblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCadId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnInserir)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnFechar)
                    .addComponent(BtnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        if(TxtCadNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Barbeiro não pode ficar em branco!");
            TxtCadNome.grabFocus();
        
        }else{
            controller.salvaBarbeiro();
            TxtCadId.setEnabled(false);
            TxtCadNome.setEnabled(false);            
            BtnInserir.setEnabled(true);
            BtnAlterar.setEnabled(true);
            BtnExcluir.setEnabled(true);
            BtnSalvar.setEnabled(false);
            BtnCancelar.setEnabled(false);
            BtnFechar.setEnabled(true);
            TxtCadNome.grabFocus();

        }

    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void TableBarbeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBarbeiroMouseClicked
        atualizaJTable();
    }//GEN-LAST:event_TableBarbeiroMouseClicked

    private void TableBarbeiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableBarbeiroKeyPressed
        atualizaJTable();
    }//GEN-LAST:event_TableBarbeiroKeyPressed

    private void TableBarbeiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableBarbeiroKeyReleased
        atualizaJTable();
    }//GEN-LAST:event_TableBarbeiroKeyReleased

    public void atualizaJTable(){
        int indicelinha = TableBarbeiro.getSelectedRow();
        TxtCadId.setText(TableBarbeiro.getValueAt(indicelinha, 0).toString());
        TxtCadNome.setText(TableBarbeiro.getValueAt(indicelinha, 1).toString());
        
        
    }    
    private void BtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserirActionPerformed
        TxtCadId.setEnabled(false);
        TxtCadNome.setEnabled(true);       
        BtnInserir.setEnabled(false);
        BtnAlterar.setEnabled(false);
        BtnExcluir.setEnabled(false);
        BtnSalvar.setEnabled(true);
        BtnCancelar.setEnabled(true);
        BtnFechar.setEnabled(false);
        TxtCadNome.grabFocus();
        helper.limpaTela();
    }//GEN-LAST:event_BtnInserirActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        if(TxtCadId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Você precisar selecionar um usuario para alterar!");
        }else{
            TxtCadId.setEnabled(false);
            TxtCadNome.setEnabled(true);            
            BtnInserir.setEnabled(false);
            BtnAlterar.setEnabled(false);
            BtnExcluir.setEnabled(false);
            BtnSalvar.setEnabled(true);
            BtnCancelar.setEnabled(true);
            BtnFechar.setEnabled(false);
            TxtCadNome.grabFocus();
        }
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        if(TxtCadId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Você precisar selecionar um barbeiro para excluir!");
        }else{
            int i = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o Barbeiro " + TxtCadNome.getText() + "?","Exclusão", JOptionPane.YES_NO_OPTION);
            if(i == JOptionPane.YES_OPTION){
                
                try {
                    controller.deletaBarbeiro();
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(CadastroBarbeiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                
                JOptionPane.showMessageDialog(null,"Barbeiro excluido com sucesso");
            }

        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFecharActionPerformed

        CadastroBarbeiroView.this.dispose();
    }//GEN-LAST:event_BtnFecharActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed

        TxtCadId.setEnabled(false);
        TxtCadNome.setEnabled(false);
        
        BtnInserir.setEnabled(true);
        BtnAlterar.setEnabled(true);
        BtnExcluir.setEnabled(true);
        BtnSalvar.setEnabled(false);
        BtnFechar.setEnabled(true);
        BtnCancelar.setEnabled(false);
        TxtCadNome.grabFocus();
    }//GEN-LAST:event_BtnCancelarActionPerformed

     private void iniciar() throws SQLException, ParseException {
        this.controller.atualizaTabela();
        
       
    }
    public JTable getTableBarbeiro() {
        return TableBarbeiro;
    }

    public void setTableBarbeiro(JTable TableBarbeiro) {
        this.TableBarbeiro = TableBarbeiro;
    }

  

    public JTextField getTxtCadId() {
        return TxtCadId;
    }

    public void setTxtCadId(JTextField TxtCadId) {
        this.TxtCadId = TxtCadId;
    }

    public JTextField getTxtCadNome() {
        return TxtCadNome;
    }

    public void setTxtCadNome(JTextField TxtCadNome) {
        this.TxtCadNome = TxtCadNome;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroBarbeiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroBarbeiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroBarbeiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroBarbeiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroBarbeiroView().setVisible(true);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(CadastroBarbeiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    java.util.logging.Logger.getLogger(CadastroBarbeiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JButton BtnInserir;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel LblNome;
    private javax.swing.JTable TableBarbeiro;
    private javax.swing.JTextField TxtCadId;
    private javax.swing.JTextField TxtCadNome;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}


